// Start screen (polish round 2, approved 2026-10-10) and the trade suggestion rules.
const fs=require('fs'),path=require('path');
let pass=0,fail=0;
const check=(n,c,d)=>{c?(pass++,console.log(`  PASS  ${n}`)):(fail++,console.log(`  FAIL  ${n}\n         ${d||''}`))};
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const a=html.indexOf('const TRADE_SUGGEST_REMODEL='),b=html.indexOf('let _tradeSuggestDismissed');
const suggestTrade=new Function(html.slice(a,b)+';return suggestTrade;')();
const GC='General Contractor';
console.log('\n=== Trade suggestion: only clear single-trade jobs ===');
check('panel 100A to 200A -> Electrical', suggestTrade('Upgrade the electrical panel from 100A to 200A',GC)==='Electrical');
check('Spanish panel job -> Electrical', suggestTrade('Cambiar el tablero eléctrico de 100A a 200A',GC)==='Electrical');
check('water heater alone -> Plumbing', suggestTrade('Replace a 40 gallon water heater in the garage',GC)==='Plumbing');
check('AC change-out -> HVAC', suggestTrade('Replace 3 ton AC condenser and air handler',GC)==='HVAC');
check('re-roof -> Roofing', suggestTrade('Re-roof 2,000 sq ft with architectural shingles',GC)==='Roofing');
check('bathroom remodel -> no suggestion', suggestTrade('Remodel the bathroom: new vanity, toilet and two outlets',GC)===null);
check('kitchen job -> no suggestion', suggestTrade('Kitchen: move the sink and add outlets',GC)===null);
check('Spanish baño -> no suggestion', suggestTrade('Remodelar el baño completo',GC)===null);
check('two trades named -> no suggestion', suggestTrade('Replace the water heater and add two outlets in the garage',GC)===null);
check('only while Trade is General Contractor', suggestTrade('Upgrade the electrical panel to 200A','Plumbing')===null);
check('too short to judge -> nothing', suggestTrade('panel',GC)===null);
check('wording: "Set trade to <trade>" + "Keep General Contractor"', /`Set trade to \$\{label\}`/.test(html)&&/Keep General Contractor/.test(html)&&/Cambiar oficio a/.test(html));
check('never switches by itself: only acceptTradeSuggestion sets the trade', (html.match(/sel\.value=pick/g)||[]).length===1&&/function acceptTradeSuggestion/.test(html));
console.log('\n=== Layout ===');
const inp=html.slice(html.indexOf('id="s-input"'),html.indexOf('<!-- /s-input -->'));
const at=s=>inp.indexOf(s);
check('job box, city, trade first; then the folds; then Analyze', at('id="scope-text"')<at('id="est-location"')&&at('id="est-location"')<at('id="est-trade"')&&at('id="est-trade"')<at('id="more-details"')&&at('id="more-details"')<at('id="your-settings"')&&at('id="your-settings"')<at('id="gen-btn"'));
check('settings are folded, not removed', ['st-oh','st-profit','st-cushion','st-lmult','labor-rate','market-adj','seg-bid','seg-labor'].every(id=>at(`id="${id}"`)>at('id="your-settings"')));
check('folded settings show a summary line', /id="settings-summary"/.test(inp)&&/function _updateSettingsSummary/.test(html));
check('"4 left" says why when signed in (bug 3)', /including any from before you signed up/.test(html)&&/contando los de antes de crear tu cuenta/.test(html));
console.log('\n=== Questions screen (polish round 3) ===');
check('"n of N" counter and bar', /id="q-count"/.test(html)&&/function updateQuestionProgress/.test(html));
check('"Other…" chip opens the text box; the box is hidden until then', /q-other-chip/.test(html)&&/function showOther/.test(html)&&/id="qother-\$\{i\}" style="display:none"/.test(html));
check('Build button stays in reach while scrolling', /<div class="d-sticky">\s*<button class="cta d-big-btn" id="calc-btn"/.test(html));
console.log('\n=== Loading screen (polish round 4, bug 5) ===');
check('checklist of five steps that follows the progress bar', /function setLoadingStepByPct/.test(html)&&/'Reading the job'/.test(html)&&/'Checking the estimate'/.test(html)&&/setLoadingStepByPct\(progShown\)/.test(html));
check('old phase lines (overhead/profit/cushion) are hidden', /<div class="loading-phase-wrap" style="display:none">/.test(html));
check('desktop gets a wider card (bug 5)', /Bug 5: the loading screen used the phone-size column on desktop/.test(html));
console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);
