// Start screen (polish round 2, approved 2026-10-10) and the trade suggestion rules.
const fs=require('fs'),path=require('path');
let pass=0,fail=0;
const check=(n,c,d)=>{c?(pass++,console.log(`  PASS  ${n}`)):(fail++,console.log(`  FAIL  ${n}\n         ${d||''}`))};
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const a=html.indexOf('const TRADE_SUGGEST_REMODEL='),b=html.indexOf('let _tradeSuggestDismissed');
const suggestTrade=new Function(html.slice(a,b)+';return suggestTrade;')();
const GC='General Contractor';
console.log('\n=== Trade suggestion: only clear single-trade jobs ===');
check('panel 100A to 200A -> Electrical', suggestTrade('Upgrade the electrical panel from 100A to 200A',GC)==='Electrical');
check('Spanish panel job -> Electrical', suggestTrade('Cambiar el tablero eléctrico de 100A a 200A',GC)==='Electrical');
check('water heater alone -> Plumbing', suggestTrade('Replace a 40 gallon water heater in the garage',GC)==='Plumbing');
check('AC change-out -> HVAC', suggestTrade('Replace 3 ton AC condenser and air handler',GC)==='HVAC');
check('re-roof -> Roofing', suggestTrade('Re-roof 2,000 sq ft with architectural shingles',GC)==='Roofing');
check('bathroom remodel -> no suggestion', suggestTrade('Remodel the bathroom: new vanity, toilet and two outlets',GC)===null);
check('kitchen job -> no suggestion', suggestTrade('Kitchen: move the sink and add outlets',GC)===null);
check('Spanish baño -> no suggestion', suggestTrade('Remodelar el baño completo',GC)===null);
check('two trades named -> no suggestion', suggestTrade('Replace the water heater and add two outlets in the garage',GC)===null);
check('only while Trade is General Contractor', suggestTrade('Upgrade the electrical panel to 200A','Plumbing')===null);
check('too short to judge -> nothing', suggestTrade('panel',GC)===null);
check('wording: "Set trade to <trade>" + "Keep General Contractor"', /`Set trade to \$\{label\}`/.test(html)&&/Keep General Contractor/.test(html)&&/Cambiar oficio a/.test(html));
check('never switches by itself: only acceptTradeSuggestion sets the trade', (html.match(/sel\.value=pick/g)||[]).length===1&&/function acceptTradeSuggestion/.test(html));
console.log('\n=== Layout ===');
const inp=html.slice(html.indexOf('id="s-input"'),html.indexOf('<!-- /s-input -->'));
const at=s=>inp.indexOf(s);
check('job box, city, trade first; then the folds; then Analyze', at('id="scope-text"')<at('id="est-location"')&&at('id="est-location"')<at('id="est-trade"')&&at('id="est-trade"')<at('id="more-details"')&&at('id="more-details"')<at('id="your-settings"')&&at('id="your-settings"')<at('id="gen-btn"'));
check('settings are folded, not removed', ['st-oh','st-profit','st-cushion','st-lmult','labor-rate','market-adj','seg-bid','seg-labor'].every(id=>at(`id="${id}"`)>at('id="your-settings"')));
check('folded settings show a summary line', /id="settings-summary"/.test(inp)&&/function _updateSettingsSummary/.test(html));
check('"4 left" says why when signed in (bug 3)', /including any from before you signed up/.test(html)&&/contando los de antes de crear tu cuenta/.test(html));
console.log('\n=== Questions screen (polish round 3) ===');
check('"n of N" counter and bar', /id="q-count"/.test(html)&&/function updateQuestionProgress/.test(html));
check('"Other…" chip opens the text box; the box is hidden until then', /q-other-chip/.test(html)&&/function showOther/.test(html)&&/id="qother-\$\{i\}" style="display:none"/.test(html));
check('Build button stays in reach while scrolling', /<div class="d-sticky">\s*<button class="cta d-big-btn" id="calc-btn"/.test(html));
console.log('\n=== Loading screen (polish round 4, bug 5) ===');
check('checklist of five steps that follows the progress bar', /function setLoadingStepByPct/.test(html)&&/'Reading the job'/.test(html)&&/'Checking the estimate'/.test(html)&&/setLoadingStepByPct\(progShown\)/.test(html));
check('old phase lines (overhead/profit/cushion) are hidden', /<div class="loading-phase-wrap" style="display:none">/.test(html));
check('desktop gets a wider card (bug 5)', /Bug 5: the loading screen used the phone-size column on desktop/.test(html));
console.log('\n=== Proposal PDF look (polish round 5) ===');
const fmt=n=>'$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const ps=html.slice(html.indexOf('function paymentSplits('),html.indexOf('async function buildClientProposalPDF('));
const {paymentSplits,initialsOf}=new Function(ps+';return {paymentSplits,initialsOf};')();
const sp=paymentSplits('30% deposit to schedule · 40% at rough-in completion · 30% upon final walkthrough.',2340);
check('payment schedule in dollars: 30/40/30 of $2,340', sp&&sp.map(r=>r.amount).join()==='702,936,702', JSON.stringify(sp));
const sp2=paymentSplits('25% de depósito para agendar · 25% al entregar materiales · 25% en la instalación inicial · 25% en la inspección final.',1001);
check('amounts always add up to the price (Spanish 25x4 of $1,001)', sp2&&sp2.reduce((t,r)=>t+r.amount,0)===1001, JSON.stringify(sp2));
check('free text that is not a % schedule falls back to plain text', paymentSplits('Net 30 after completion',5000)===null);
check('initials when there is no logo', initialsOf('Acme Plumbing LLC')==='AP'&&initialsOf('')==='');
check('PDF and preview both use the dollar boxes', (html.match(/paymentSplits\(P\.payment,P\.price\)/g)||[]).length===2);
console.log('\n=== Sign-up and pricing (polish round 6) ===');
const panel=html.slice(html.indexOf('<div id="topbar-auth-panel"'),html.indexOf('<div id="auth-signed-in"'));
check('Google first, then email', panel.indexOf('signInWithGoogle()')<panel.indexOf('id="auth-email"'));
check('plain words about the free account (EN/ES)', /Free account: \$\{more\} more estimates and PDF downloads\./.test(html)&&/Cuenta gratis: \$\{more\} estimados más/.test(html));
check('"Create free account" button', /'Create free account'/.test(html)&&/'Crear cuenta gratis'/.test(html));
check("Founder's Club card stays hidden until its Stripe link exists", /const FOUNDERS_LINK = '';/.test(html)&&/fc\.hidden=!FOUNDERS_LINK/.test(html));
console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);
