import { useState, useEffect, useRef } from 'react'
import { motion, AnimatePresence, animate } from 'framer-motion'

const LOOP = 52000

const PHASES = {
  nav:            500,
  cameraRoll:     3500,
  select:         4900,
  uploadStart:    5900,
  scanLine:       6200,
  uploadDone:     9900,
  marginCard:     11100,
  marginOH:       12100,
  marginPT:       13100,
  marginRC:       14100,
  marginLock:     15300,
  formSection:    16500,
  jobType:        17000,
  location:       18100,
  size:           19200,
  runBtn:         20100,
  runTap:         21200,
  permitLabel:    22000,
  permitLoading:  22400,
  permitRows:     25700,
  estimateLabel:  28200,
  estimateRows:   28900,
  total:          31500,
  bid:            33200,
  exportBtn:      34700,
  internalDoc:    36700,
  proposalDoc:    40700,
  badge:          43200,
  addHome:        45700,
  logo:           47700,
}

const STRINGS_EN = {
  eyebrow: 'Blueprint → Estimate',
  market: 'Market',
  selectMarket: 'Select Market',
  markets: [
    { region: 'MIAMI-DADE', cities: ['Sunny Isles Beach, FL', 'Aventura, FL', 'Hallandale Beach, FL'] },
  ],
  targetCity: 'Sunny Isles Beach, FL',
  newEstimate: 'New Estimate',
  uploadPlans: 'Upload Plans',
  uploadingPlans: 'Uploading plans...',
  plansReady: '✓ Plans ready',
  plansRead: '✓ Plans read',
  marginSettings: 'Margin Settings',
  overhead: 'Overhead',
  profitTarget: 'Profit Target',
  riskCushion: 'Risk Cushion',
  protected: 'Protected',
  fixedPrice: 'Fixed',
  tm: 'T&M',
  ownCrew: 'Own',
  subs: 'Subs',
  mixed: 'Mixed',
  jobDetails: 'Job Details',
  jobTypeLabel: 'Job Type',
  jobTypeValue: 'Roofing Replacement',
  locationLabel: 'Location',
  locationValue: 'Sunny Isles Beach, FL',
  sizeLabel: 'Size',
  sizeValue: '2,400 sq ft',
  getEstimate: 'Get Estimate →',
  permitData: 'Permit Data',
  pullingPermit: 'Indexing Miami-Dade permit schedule...',
  cityFee: 'City Application Fee',
  stateFee: 'State Filing Fee',
  inspections: 'Required Inspections (×2)',
  totalFees: 'Total Fees',
  estimate: 'Estimate',
  materials: 'Materials',
  labor: 'Labor',
  permitsLabel: 'Permits & Fees',
  overheadRow: 'Overhead (12%)',
  total: 'Total',
  bidRange: 'Bid Range',
  clientProposal: 'Client Proposal ↗',
  internalCost: 'Internal Cost',
  addHome: 'Add Even to your Home Screen',
  addHomeSub: 'Tap ↑ Share → "Add to Home Screen"',
  internal: {
    title: 'Internal Cost Sheet',
    confidential: 'Confidential',
    subtitle: 'Roofing Replacement · Sunny Isles Beach, FL',
    rows: [
      ['Materials', '$12,450'],
      ['Labor', '$8,200'],
      ['Permits & Fees', '$1,217'],
      ['Overhead (12%)', '$2,630'],
    ],
    directCost: 'Direct Cost',
    grossMargin: 'Gross Margin',
    netProfit: 'Net Profit',
    ref: 'Job Ref',
    refVal: 'SFB-2024',
    clientTotal: 'Client Total',
  },
  proposal: {
    preparedFor: 'Prepared For',
    clientName: 'J. Martinez',
    clientCity: 'Sunny Isles Beach, FL 33160',
    dateLabel: 'Date',
    dateValue: 'June 28, 2026',
    ref: 'Ref: SFB-2024',
    jobDescription: 'Roofing Replacement — 2,400 sq ft',
    scopeTitle: 'Scope of Work',
    scope: [
      'Remove and dispose of existing roofing materials',
      'Install premium 30-year architectural shingles',
      'Replace underlayment and moisture barrier',
      'All permit filing and fees included',
      'Post-installation cleanup and final inspection',
    ],
    totalLabel: 'Total',
    paymentTitle: 'Payment Terms',
    payments: [['50% due at signing', '$12,248'], ['50% due on completion', '$12,249']],
    footer: 'Generated by Even · even-os.com',
  },
}

const STRINGS_ES = {
  eyebrow: 'Plano → Estimado',
  market: 'Mercado',
  selectMarket: 'Seleccionar Mercado',
  markets: [
    { region: 'MIAMI-DADE', cities: ['Sunny Isles Beach, FL', 'Aventura, FL', 'Hallandale Beach, FL'] },
  ],
  targetCity: 'Sunny Isles Beach, FL',
  newEstimate: 'Nuevo Estimado',
  uploadPlans: 'Subir Planos',
  uploadingPlans: 'Subiendo planos...',
  plansReady: '✓ Planos listos',
  plansRead: '✓ Planos leídos',
  marginSettings: 'Configuración de Margen',
  overhead: 'Gastos Generales',
  profitTarget: 'Meta de Ganancia',
  riskCushion: 'Colchón de Riesgo',
  protected: 'Protegido',
  fixedPrice: 'Fijo',
  tm: 'T&M',
  ownCrew: 'Propio',
  subs: 'Subs',
  mixed: 'Mixto',
  jobDetails: 'Detalles del Trabajo',
  jobTypeLabel: 'Tipo de Trabajo',
  jobTypeValue: 'Reemplazo de Techo',
  locationLabel: 'Ubicación',
  locationValue: 'Sunny Isles Beach, FL',
  sizeLabel: 'Tamaño',
  sizeValue: '2,400 pies cuadrados',
  getEstimate: 'Obtener Estimado →',
  permitData: 'Datos de Permisos',
  pullingPermit: 'Indexando permisos Miami-Dade...',
  cityFee: 'Tarifa de Solicitud Ciudad',
  stateFee: 'Tarifa Estatal',
  inspections: 'Inspecciones Requeridas (×2)',
  totalFees: 'Total de Tarifas',
  estimate: 'Estimado',
  materials: 'Materiales',
  labor: 'Mano de Obra',
  permitsLabel: 'Permisos y Tarifas',
  overheadRow: 'Gastos Generales (12%)',
  total: 'Total',
  bidRange: 'Rango de Propuesta',
  clientProposal: 'Propuesta al Cliente ↗',
  internalCost: 'Costo Interno',
  addHome: 'Agrega Even a tu Pantalla de Inicio',
  addHomeSub: 'Toca ↑ Compartir → "Agregar a Inicio"',
  internal: {
    title: 'Hoja de Costos Internos',
    confidential: 'Confidencial',
    subtitle: 'Reemplazo de Techo · Sunny Isles Beach, FL',
    rows: [
      ['Materiales', '$12,450'],
      ['Mano de Obra', '$8,200'],
      ['Permisos y Tarifas', '$1,217'],
      ['Gastos Generales (12%)', '$2,630'],
    ],
    directCost: 'Costo Directo',
    grossMargin: 'Margen Bruto',
    netProfit: 'Utilidad Neta',
    ref: 'Ref. Trabajo',
    refVal: 'SFB-2024',
    clientTotal: 'Total del Cliente',
  },
  proposal: {
    preparedFor: 'Preparado Para',
    clientName: 'M. Reyes',
    clientCity: 'Sunny Isles Beach, FL 33160',
    dateLabel: 'Fecha',
    dateValue: '28 de junio, 2026',
    ref: 'Ref: SFB-2024',
    jobDescription: 'Reemplazo de Techo — 2,400 pies²',
    scopeTitle: 'Alcance del Trabajo',
    scope: [
      'Retirar y desechar los materiales del techo existente',
      'Instalar tejas arquitectónicas premium de 30 años',
      'Reemplazar la base y la barrera de humedad',
      'Todos los permisos y tarifas incluidos',
      'Limpieza post-instalación e inspección final',
    ],
    totalLabel: 'Total',
    paymentTitle: 'Términos de Pago',
    payments: [['50% al firmar', '$12,248'], ['50% al completar', '$12,249']],
    footer: 'Generado por Even · even-os.com',
  },
}

// ── PHONE FRAME ─────────────────────────────────────────────────────────────────
function StepNode({ n, label, active }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.25rem', flexShrink: 0 }}>
      <motion.div
        animate={{ background: active ? '#D4AF37' : 'rgba(255,255,255,0.07)', color: active ? '#0A0A0A' : 'rgba(255,255,255,0.3)' }}
        transition={{ duration: 0.45 }}
        style={{ width: 26, height: 26, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', border: active ? 'none' : '1.5px solid rgba(255,255,255,0.15)', fontSize: '0.62rem', fontWeight: 900, fontFamily: 'monospace' }}
      >{n}</motion.div>
      <motion.span
        animate={{ color: active ? '#D4AF37' : 'rgba(255,255,255,0.3)' }}
        transition={{ duration: 0.45 }}
        style={{ fontSize: '0.37rem', letterSpacing: '0.18em', fontFamily: 'monospace', textTransform: 'uppercase' }}
      >{label}</motion.span>
    </div>
  )
}

function StepProgress({ activeStep }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', padding: '0.55rem 1.4rem 0.35rem', borderBottom: '1px solid rgba(255,255,255,0.05)', flexShrink: 0 }}>
      <StepNode n={1} label="SCOPE"    active={activeStep >= 1} />
      <div style={{ flex: 1, height: '1px', background: 'rgba(255,255,255,0.1)', margin: '0 0.35rem 0.7rem' }} />
      <StepNode n={2} label="REFINE"   active={activeStep >= 2} />
      <div style={{ flex: 1, height: '1px', background: 'rgba(255,255,255,0.1)', margin: '0 0.35rem 0.7rem' }} />
      <StepNode n={3} label="ESTIMATE" active={activeStep >= 3} />
    </div>
  )
}

function PhoneFrame({ children }) {
  return (
    <div style={{
      position: 'relative',
      width: 'min(360px, 90vw)',
      flexShrink: 0,
      background: 'linear-gradient(155deg, #282828 0%, #181818 50%, #0e0e0e 100%)',
      borderRadius: '50px',
      padding: '11px',
      boxShadow: `
        0 0 0 1px rgba(212,175,55,0.22),
        0 2px 0 2px rgba(0,0,0,0.95),
        0 8px 0 2px rgba(0,0,0,0.8),
        0 18px 0 2px rgba(0,0,0,0.55),
        0 32px 0 2px rgba(0,0,0,0.3),
        0 60px 120px -10px rgba(0,0,0,0.98),
        0 100px 200px -20px rgba(0,0,0,0.7),
        inset 0 1px 0 rgba(255,255,255,0.09),
        inset 0 0 0 1px rgba(255,255,255,0.04)
      `,
    }}>
      {/* Gold top-edge accent */}
      <div style={{ position: 'absolute', top: 0, left: '22%', right: '22%', height: '1px', background: 'linear-gradient(90deg, transparent, rgba(212,175,55,0.55), transparent)', borderRadius: '999px' }} />

      {/* Screen */}
      <div style={{
        background: '#0A0A0A',
        borderRadius: '40px',
        overflow: 'hidden',
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        height: 'min(740px, 86vh)',
        boxShadow: 'inset 0 0 60px rgba(0,0,0,0.95)',
      }}>
        {/* Dynamic Island */}
        <div style={{ position: 'absolute', top: 12, left: '50%', transform: 'translateX(-50%)', width: 120, height: 32, background: '#000', borderRadius: '22px', zIndex: 20 }} />
        {/* Status bar space */}
        <div style={{ height: 52, flexShrink: 0 }} />
        {/* Content */}
        <div style={{ flex: 1, overflow: 'hidden', position: 'relative', display: 'flex', flexDirection: 'column' }}>
          {children}
        </div>
        {/* Home indicator */}
        <div style={{ display: 'flex', justifyContent: 'center', padding: '6px 0 16px', flexShrink: 0 }}>
          <div style={{ width: 120, height: 4, background: 'rgba(255,255,255,0.1)', borderRadius: '999px' }} />
        </div>
      </div>

      {/* Side buttons */}
      {[108, 160, 212].map((top, i) => (
        <div key={i} style={{ position: 'absolute', left: -3, top, width: 3, height: i === 0 ? 30 : 56, background: '#2a2a2a', borderRadius: '2px 0 0 2px' }} />
      ))}
      <div style={{ position: 'absolute', right: -3, top: 160, width: 3, height: 75, background: '#2a2a2a', borderRadius: '0 2px 2px 0' }} />
    </div>
  )
}

// ── BLUEPRINT ──────────────────────────────────────────────────────────────────
function FloorPlan({ selected, scanning, analyzed, plansRead }) {
  const wall  = 'rgba(255,255,255,0.6)'
  const inner = 'rgba(255,255,255,0.25)'
  const door  = 'rgba(255,255,255,0.14)'
  const lbl   = 'rgba(212,175,55,0.9)'
  const dim   = 'rgba(255,255,255,0.2)'
  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      style={{
        width: '100%', background: '#0A0A0A',
        border: `1.5px solid ${selected ? 'rgba(212,175,55,0.9)' : 'rgba(255,255,255,0.1)'}`,
        borderRadius: '6px', position: 'relative', overflow: 'hidden',
        transition: 'border-color 0.4s ease', padding: '0.75rem',
        boxShadow: selected ? '0 0 20px rgba(212,175,55,0.12)' : 'none',
      }}
    >
      <div style={{
        position: 'absolute', inset: 0,
        backgroundImage: [
          'repeating-linear-gradient(90deg, rgba(255,255,255,0.03) 0px, rgba(255,255,255,0.03) 1px, transparent 1px, transparent 14px)',
          'repeating-linear-gradient(0deg, rgba(255,255,255,0.03) 0px, rgba(255,255,255,0.03) 1px, transparent 1px, transparent 14px)',
        ].join(','),
      }} />
      <svg viewBox="0 0 200 130" style={{ width: '100%', height: 'auto', display: 'block', position: 'relative' }}>
        <rect x="10" y="10" width="180" height="110" fill="none" stroke={wall} strokeWidth="2.5" />
        <line x1="110" y1="10" x2="110" y2="80" stroke={inner} strokeWidth="1.5" />
        <line x1="110" y1="55" x2="190" y2="55" stroke={inner} strokeWidth="1.5" />
        <line x1="10" y1="75" x2="110" y2="75" stroke={inner} strokeWidth="1.5" />
        <path d="M110 75 Q95 75 95 60" fill="none" stroke={door} strokeWidth="1" />
        <path d="M110 55 Q125 55 125 40" fill="none" stroke={door} strokeWidth="1" />
        <line x1="30" y1="10" x2="60" y2="10" stroke="rgba(255,255,255,0.7)" strokeWidth="2.5" />
        <line x1="130" y1="10" x2="170" y2="10" stroke="rgba(255,255,255,0.7)" strokeWidth="2.5" />
        <line x1="190" y1="30" x2="190" y2="50" stroke="rgba(255,255,255,0.7)" strokeWidth="2.5" />
        <text x="55" y="48" textAnchor="middle" style={{ fontSize: '7px', fill: lbl, fontFamily: 'monospace', fontWeight: 700, letterSpacing: '0.1em' }}>LIVING</text>
        <text x="55" y="95" textAnchor="middle" style={{ fontSize: '7px', fill: lbl, fontFamily: 'monospace', fontWeight: 700, letterSpacing: '0.1em' }}>KITCHEN</text>
        <text x="150" y="38" textAnchor="middle" style={{ fontSize: '7px', fill: lbl, fontFamily: 'monospace', fontWeight: 700, letterSpacing: '0.1em' }}>BED 1</text>
        <text x="150" y="90" textAnchor="middle" style={{ fontSize: '7px', fill: lbl, fontFamily: 'monospace', fontWeight: 700, letterSpacing: '0.1em' }}>BED 2</text>
        <line x1="10" y1="125" x2="190" y2="125" stroke={dim} strokeWidth="0.8" />
        <text x="100" y="123" textAnchor="middle" style={{ fontSize: '5.5px', fill: 'rgba(255,255,255,0.22)', fontFamily: 'monospace' }}>48 ft</text>
        <line x1="4" y1="10" x2="4" y2="120" stroke={dim} strokeWidth="0.8" />
        <text x="2" y="68" textAnchor="middle" style={{ fontSize: '5.5px', fill: 'rgba(255,255,255,0.22)', fontFamily: 'monospace' }} transform="rotate(-90 2 68)">50 ft</text>
      </svg>
      {scanning && !analyzed && (
        <motion.div
          initial={{ top: '0%' }} animate={{ top: '100%' }}
          transition={{ duration: 1.6, ease: 'linear' }}
          style={{
            position: 'absolute', left: 0, right: 0, height: '3px',
            background: 'linear-gradient(90deg, transparent 0%, rgba(212,175,55,0.4) 15%, rgba(212,175,55,1) 50%, rgba(212,175,55,0.4) 85%, transparent 100%)',
            boxShadow: '0 0 20px 4px rgba(212,175,55,0.65), 0 0 50px rgba(212,175,55,0.25)',
            pointerEvents: 'none',
          }}
        />
      )}
      {analyzed && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.4 }}
          style={{ position: 'absolute', top: 6, right: 6, background: 'rgba(212,175,55,0.1)', border: '1px solid rgba(212,175,55,0.5)', borderRadius: '3px', padding: '3px 7px' }}>
          <span style={{ color: '#D4AF37', fontSize: '0.52rem', fontWeight: 700, fontFamily: 'monospace' }}>{plansRead}</span>
        </motion.div>
      )}
      {selected && !analyzed && (
        <div style={{ position: 'absolute', top: 6, right: 6, width: 18, height: 18, borderRadius: '50%', background: '#D4AF37', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <svg width="9" height="7" viewBox="0 0 9 7" fill="none">
            <path d="M1 3.5L3.5 6L8 1" stroke="#0A0A0A" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </div>
      )}
    </motion.div>
  )
}

// ── MARGIN SLIDER ───────────────────────────────────────────────────────────────
function MarginSlider({ label, targetPct, color, active }) {
  const [displayPct, setDisplayPct] = useState(0)
  const barRef = useRef(null)
  const MAX = 30

  useEffect(() => {
    if (!active) {
      setDisplayPct(0)
      if (barRef.current) barRef.current.style.width = '0%'
      return
    }
    const ctrl = animate(0, targetPct, {
      duration: 0.85,
      ease: [0.16, 1, 0.3, 1],
      onUpdate: v => {
        setDisplayPct(Math.round(v))
        if (barRef.current) barRef.current.style.width = `${(v / MAX) * 100}%`
      },
    })
    return () => ctrl.stop()
  }, [active, targetPct])

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.26rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <span style={{ color: 'rgba(255,255,255,0.38)', fontSize: '0.58rem', fontFamily: 'monospace' }}>{label}</span>
        <span style={{ color, fontSize: '0.65rem', fontWeight: 700, fontVariantNumeric: 'tabular-nums', fontFamily: 'monospace' }}>{displayPct}%</span>
      </div>
      <div style={{ height: '3px', background: 'rgba(255,255,255,0.06)', borderRadius: '999px', overflow: 'hidden' }}>
        <div ref={barRef} style={{ height: '100%', width: '0%', background: color, borderRadius: '999px', boxShadow: `0 0 8px ${color}66` }} />
      </div>
    </div>
  )
}

// ── HELPERS ────────────────────────────────────────────────────────────────────
function TypeIn({ text, active, speed = 38 }) {
  const [shown, setShown] = useState('')
  const ref = useRef(null)
  useEffect(() => {
    if (!active) { setShown(''); return }
    let i = 0
    ref.current = setInterval(() => {
      i++
      setShown(text.slice(0, i))
      if (i >= text.length) clearInterval(ref.current)
    }, speed)
    return () => clearInterval(ref.current)
  }, [active, text])
  return <>{shown}{shown.length < text.length && active && <span style={{ opacity: 0.4 }}>|</span>}</>
}

function CountUp({ to, running }) {
  const [val, setVal] = useState(0)
  useEffect(() => {
    if (!running) { setVal(0); return }
    const ctrl = animate(0, to, { duration: 1.6, ease: [0.16, 1, 0.3, 1], onUpdate: v => setVal(Math.floor(v)) })
    return () => ctrl.stop()
  }, [running, to])
  return <>{val.toLocaleString()}</>
}

function FormRow({ label, value, active }) {
  return (
    <AnimatePresence>
      {active && (
        <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }} style={{ display: 'flex', flexDirection: 'column', gap: '0.2rem' }}>
          <div style={{ color: 'rgba(255,255,255,0.22)', fontSize: '0.52rem', letterSpacing: '0.2em', textTransform: 'uppercase', fontWeight: 600, fontFamily: 'monospace' }}>{label}</div>
          <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '4px', padding: '0.5rem 0.7rem', color: '#fff', fontSize: '0.75rem', fontWeight: 500, fontFamily: 'monospace', minHeight: '2.1rem' }}>
            <TypeIn text={value} active={active} />
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

function Row({ label, value, delay, visible, gold }) {
  return (
    <AnimatePresence>
      {visible && (
        <motion.div initial={{ opacity: 0, x: -5 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.4, delay }}
          style={{ display: 'flex', justifyContent: 'space-between', padding: '0.4rem 0', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
          <span style={{ color: 'rgba(255,255,255,0.32)', fontSize: '0.67rem', fontFamily: 'monospace' }}>{label}</span>
          <span style={{ color: gold ? '#D4AF37' : '#fff', fontSize: '0.7rem', fontWeight: 700, fontVariantNumeric: 'tabular-nums', fontFamily: 'monospace' }}>{value}</span>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

function SectionLabel({ children, visible }) {
  return (
    <AnimatePresence>
      {visible && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.5 }}
          style={{ color: '#D4AF37', fontSize: '0.46rem', letterSpacing: '0.4em', textTransform: 'uppercase', fontWeight: 800, marginBottom: '0.5rem', fontFamily: 'monospace', textShadow: '0 0 12px rgba(212,175,55,0.4)' }}>
          {children}
        </motion.div>
      )}
    </AnimatePresence>
  )
}

// ── MAIN COMPONENT ─────────────────────────────────────────────────────────────
function ExplainerBase({ strings }) {
  const [p, setP] = useState({})
  const timers = useRef([])
  const [uploadPct, setUploadPct] = useState(0)

  function reset() {
    timers.current.forEach(t => typeof t === 'function' ? t() : clearTimeout(t))
    timers.current = []
    setP({})
    setUploadPct(0)
  }

  function run() {
    reset()
    Object.entries(PHASES).forEach(([key, delay]) => {
      timers.current.push(setTimeout(() => setP(prev => ({ ...prev, [key]: true })), delay))
    })
    timers.current.push(setTimeout(() => {
      const ctrl = animate(0, 100, { duration: 3.5, ease: 'easeInOut', onUpdate: v => setUploadPct(Math.floor(v)) })
      timers.current.push(() => ctrl.stop())
    }, PHASES.uploadStart))
    timers.current.push(setTimeout(run, LOOP))
  }

  useEffect(() => { run(); return reset }, [])

  // Scene resolver — doc overlay takes priority over scrollable content
  const docScene = p.proposalDoc ? 'proposal' : p.internalDoc ? 'internal' : null
  const showApp = !docScene
  const activeStep = p.permitLabel ? 3 : p.marginCard ? 2 : 1

  return (
    <div style={{
      width: '100vw', height: '100vh', background: '#0A0A0A',
      backgroundImage: [
        'repeating-linear-gradient(60deg, rgba(212,175,55,0.042) 0px, rgba(212,175,55,0.042) 1px, transparent 1px, transparent 44px)',
        'repeating-linear-gradient(-60deg, rgba(212,175,55,0.042) 0px, rgba(212,175,55,0.042) 1px, transparent 1px, transparent 44px)',
      ].join(','),
      display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
      fontFamily: 'Inter, system-ui, sans-serif', position: 'relative', overflow: 'hidden',
    }}>

      {/* Vignette */}
      <div style={{
        position: 'absolute', inset: 0, pointerEvents: 'none',
        background: 'radial-gradient(ellipse 70% 65% at 50% 50%, transparent 0%, #0A0A0A 100%)',
      }} />

      {/* Eyebrow — cycles with active step */}
      {p.nav && (
        <AnimatePresence mode="wait">
          <motion.div key={activeStep}
            initial={{ opacity: 0, y: -5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 5 }}
            transition={{ duration: 0.55, ease: [0.16, 1, 0.3, 1] }}
            style={{ position: 'absolute', top: '1.5rem', left: 0, right: 0, textAlign: 'center', zIndex: 10 }}
          >
            <span style={{ color: '#D4AF37', fontSize: '0.52rem', fontWeight: 800, letterSpacing: '0.45em', textTransform: 'uppercase', fontFamily: 'monospace', textShadow: '0 0 20px rgba(212,175,55,0.35)' }}>
              {['SCOPE', 'REFINE', 'ESTIMATE'][activeStep - 1]}
            </span>
          </motion.div>
        </AnimatePresence>
      )}

      <PhoneFrame>
        {/* Nav bar */}
        <AnimatePresence>
          {p.nav && (
            <motion.div key="nav"
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.5 }}
              style={{ position: 'relative', flexShrink: 0 }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.7rem 1rem 0.6rem', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                <img src="/logo.png" alt="Even" style={{ height: '1rem', objectFit: 'contain' }} onError={e => { e.target.style.display = 'none' }} />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Step progress — persists, activeStep updates as sequence advances */}
        {p.nav && <StepProgress activeStep={activeStep} />}

        {/* Main content area — switches between scrollable app and doc overlays */}
        <div style={{ flex: 1, overflow: 'hidden', position: 'relative', display: 'flex', flexDirection: 'column' }}>

          {/* Intro / onboarding screen — matches real app entry state */}
          <AnimatePresence>
            {p.nav && !p.cameraRoll && (
              <motion.div key="intro-screen"
                initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, y: -6 }}
                transition={{ duration: 0.55, ease: [0.16, 1, 0.3, 1] }}
                style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '1.5rem', gap: '0.85rem', textAlign: 'center', zIndex: 5 }}
              >
                <img src="/logo.png" alt="Even" style={{ height: '2.8rem', objectFit: 'contain' }}
                  onError={e => { e.target.style.display = 'none' }} />
                <span style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 900, letterSpacing: '-0.02em', lineHeight: 1 }}>
                  even<span style={{ color: '#D4AF37' }}>.</span>
                </span>
                <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.64rem', lineHeight: 1.6, margin: 0, maxWidth: '190px' }}>
                  Scope in. Winning bid out.<br />Built for contractors.
                </p>
              </motion.div>
            )}
          </AnimatePresence>

          <AnimatePresence mode="wait">

            {/* ── APP CONTENT (scrollable) ── */}
            {showApp && (
              <motion.div key="app"
                initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, filter: 'blur(4px)', scale: 0.97 }}
                transition={{ duration: 0.45, ease: [0.4, 0, 1, 1] }}
                style={{ flex: 1, overflowY: 'auto', padding: '0.75rem 1rem', display: 'flex', flexDirection: 'column', gap: '1.1rem' }}
              >

                {/* Blueprint / upload */}
                <AnimatePresence>
                  {p.cameraRoll && !p.marginCard && (
                    <motion.div key="upload" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.5 }}>
                      <div style={{ color: 'rgba(255,255,255,0.22)', fontSize: '0.52rem', letterSpacing: '0.2em', textTransform: 'uppercase', fontWeight: 600, marginBottom: '0.6rem', fontFamily: 'monospace' }}>
                        {strings.uploadPlans}
                      </div>
                      <FloorPlan selected={p.select} scanning={p.scanLine && !p.uploadDone} analyzed={p.uploadDone} plansRead={strings.plansRead} />
                      <AnimatePresence>
                        {p.uploadStart && (
                          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} style={{ marginTop: '0.6rem' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.3rem' }}>
                              <span style={{ color: 'rgba(255,255,255,0.28)', fontSize: '0.6rem', fontFamily: 'monospace' }}>
                                {p.uploadDone ? strings.plansReady : strings.uploadingPlans}
                              </span>
                              <span style={{ color: p.uploadDone ? '#D4AF37' : 'rgba(255,255,255,0.22)', fontSize: '0.6rem', fontVariantNumeric: 'tabular-nums', fontFamily: 'monospace' }}>
                                {p.uploadDone ? '100%' : `${uploadPct}%`}
                              </span>
                            </div>
                            <div style={{ height: '2px', background: 'rgba(255,255,255,0.05)', borderRadius: '999px', overflow: 'hidden' }}>
                              <div style={{ height: '100%', width: p.uploadDone ? '100%' : `${uploadPct}%`, background: p.uploadDone ? 'linear-gradient(90deg,#BF953F,#FCF6BA,#D4AF37)' : 'rgba(212,175,55,0.45)', borderRadius: '999px', transition: 'width 0.1s, background 0.4s', boxShadow: p.uploadDone ? '0 0 8px rgba(212,175,55,0.6)' : 'none' }} />
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Margin settings card */}
                <AnimatePresence>
                  {p.marginCard && !p.formSection && (
                    <motion.div key="margin"
                      initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}
                      transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
                      style={{
                        background: '#141414',
                        border: '1px solid rgba(212,175,55,0.18)',
                        borderRadius: '8px',
                        padding: '0.8rem 0.9rem',
                        display: 'flex', flexDirection: 'column', gap: '0.65rem',
                      }}
                    >
                      {/* Card header */}
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <span style={{ color: 'rgba(255,255,255,0.22)', fontSize: '0.48rem', letterSpacing: '0.3em', textTransform: 'uppercase', fontFamily: 'monospace' }}>{strings.marginSettings}</span>
                        <AnimatePresence>
                          {p.marginLock && (
                            <motion.div
                              initial={{ opacity: 0, scale: 0.6 }}
                              animate={{ opacity: 1, scale: 1 }}
                              transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                              style={{
                                background: 'rgba(212,175,55,0.1)',
                                border: '1px solid rgba(212,175,55,0.45)',
                                borderRadius: '999px',
                                padding: '0.18rem 0.6rem',
                                display: 'flex', alignItems: 'center', gap: '0.28rem',
                                boxShadow: '0 0 12px rgba(212,175,55,0.2)',
                              }}
                            >
                              <span style={{ color: '#D4AF37', fontSize: '0.65rem', fontWeight: 900, fontVariantNumeric: 'tabular-nums', fontFamily: 'monospace' }}>32%</span>
                              <span style={{ color: 'rgba(212,175,55,0.55)', fontSize: '0.42rem', letterSpacing: '0.1em', textTransform: 'uppercase', fontFamily: 'monospace' }}>{strings.protected}</span>
                            </motion.div>
                          )}
                        </AnimatePresence>
                      </div>

                      {/* Sliders */}
                      <MarginSlider label={strings.overhead}     targetPct={12} color="#E8872A" active={p.marginOH} />
                      <MarginSlider label={strings.profitTarget} targetPct={15} color="#3DBE6C" active={p.marginPT} />
                      <MarginSlider label={strings.riskCushion}  targetPct={5}  color="#E85555" active={p.marginRC} />

                      {/* Toggles */}
                      <div style={{ display: 'flex', gap: '0.45rem', marginTop: '0.1rem' }}>
                        {/* Fixed / T&M */}
                        <div style={{ flex: 1, display: 'flex', background: 'rgba(255,255,255,0.04)', borderRadius: '5px', padding: '2px', overflow: 'hidden' }}>
                          <div style={{ flex: 1, background: '#D4AF37', color: '#0A0A0A', fontSize: '0.48rem', fontWeight: 900, textAlign: 'center', padding: '0.32rem 0', borderRadius: '3px', fontFamily: 'monospace', letterSpacing: '0.05em' }}>{strings.fixedPrice}</div>
                          <div style={{ flex: 1, color: 'rgba(255,255,255,0.2)', fontSize: '0.48rem', textAlign: 'center', padding: '0.32rem 0', fontFamily: 'monospace' }}>{strings.tm}</div>
                        </div>
                        {/* Crew type */}
                        <div style={{ flex: 1.6, display: 'flex', background: 'rgba(255,255,255,0.04)', borderRadius: '5px', padding: '2px', overflow: 'hidden' }}>
                          <div style={{ flex: 1, color: 'rgba(255,255,255,0.18)', fontSize: '0.48rem', textAlign: 'center', padding: '0.32rem 0', fontFamily: 'monospace' }}>{strings.ownCrew}</div>
                          <div style={{ flex: 1, color: 'rgba(255,255,255,0.18)', fontSize: '0.48rem', textAlign: 'center', padding: '0.32rem 0', fontFamily: 'monospace' }}>{strings.subs}</div>
                          <div style={{ flex: 1.2, background: '#D4AF37', color: '#0A0A0A', fontSize: '0.48rem', fontWeight: 900, textAlign: 'center', padding: '0.32rem 0', borderRadius: '3px', fontFamily: 'monospace' }}>{strings.mixed}</div>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Form */}
                <AnimatePresence>
                  {p.formSection && !p.permitLabel && (
                    <motion.div key="form" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} transition={{ duration: 0.5 }}
                      style={{ display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
                      <div style={{ color: 'rgba(255,255,255,0.22)', fontSize: '0.52rem', letterSpacing: '0.2em', textTransform: 'uppercase', fontWeight: 600, fontFamily: 'monospace' }}>
                        {strings.jobDetails}
                      </div>
                      <FormRow label={strings.jobTypeLabel} value={strings.jobTypeValue} active={p.jobType} />
                      <FormRow label={strings.locationLabel} value={strings.locationValue} active={p.location} />
                      <FormRow label={strings.sizeLabel} value={strings.sizeValue} active={p.size} />
                      <AnimatePresence>
                        {p.runBtn && (
                          <motion.div initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }} style={{ marginTop: '0.2rem' }}>
                            <motion.div
                              animate={p.runTap ? { scale: [1, 0.96, 1] } : {}}
                              transition={{ duration: 0.2 }}
                              style={{
                                background: 'linear-gradient(135deg, #BF953F 0%, #FCF6BA 40%, #D4AF37 60%, #B38728 100%)',
                                color: '#0A0A0A', borderRadius: '4px', padding: '0.65rem', textAlign: 'center',
                                fontSize: '0.68rem', fontWeight: 900, letterSpacing: '0.1em', textTransform: 'uppercase', fontFamily: 'monospace',
                                boxShadow: p.runTap ? '0 0 30px rgba(212,175,55,0.4)' : '0 0 20px rgba(212,175,55,0.2)',
                              }}
                            >
                              {strings.getEstimate}
                            </motion.div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Permit data */}
                <div>
                  <SectionLabel visible={p.permitLabel}>{strings.permitData}</SectionLabel>
                  <AnimatePresence>
                    {p.permitLoading && !p.permitRows && (
                      <motion.div key="permit-load" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                        style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', padding: '0.2rem 0' }}>
                        <motion.div animate={{ rotate: 360 }} transition={{ duration: 0.9, repeat: Infinity, ease: 'linear' }}
                          style={{ width: 10, height: 10, borderRadius: '50%', border: '1.5px solid rgba(212,175,55,0.15)', borderTopColor: '#D4AF37' }} />
                        <span style={{ color: 'rgba(255,255,255,0.2)', fontSize: '0.62rem', fontFamily: 'monospace' }}>{strings.pullingPermit}</span>
                      </motion.div>
                    )}
                  </AnimatePresence>
                  {p.permitRows && (
                    <div>
                      <Row label={strings.cityFee}    value="$847"   delay={0}    visible={p.permitRows} />
                      <Row label={strings.stateFee}   value="$120"   delay={0.15} visible={p.permitRows} />
                      <Row label={strings.inspections} value="$250"  delay={0.3}  visible={p.permitRows} />
                      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6 }}
                        style={{ display: 'flex', justifyContent: 'space-between', paddingTop: '0.4rem' }}>
                        <span style={{ color: 'rgba(255,255,255,0.16)', fontSize: '0.56rem', letterSpacing: '0.12em', textTransform: 'uppercase', fontFamily: 'monospace' }}>{strings.totalFees}</span>
                        <span style={{ color: '#D4AF37', fontWeight: 800, fontSize: '0.7rem', fontFamily: 'monospace', textShadow: '0 0 10px rgba(212,175,55,0.4)' }}>$1,217</span>
                      </motion.div>
                    </div>
                  )}
                </div>

                {/* Estimate */}
                <div>
                  <SectionLabel visible={p.estimateLabel}>{strings.estimate}</SectionLabel>
                  {p.estimateRows && (
                    <div>
                      <Row label={strings.materials}   value="$12,450" delay={0}    visible={p.estimateRows} />
                      <Row label={strings.labor}       value="$8,200"  delay={0.14} visible={p.estimateRows} />
                      <Row label={strings.permitsLabel} value="$1,217" delay={0.28} visible={p.estimateRows} />
                      <Row label={strings.overheadRow} value="$2,630"  delay={0.42} visible={p.estimateRows} />
                    </div>
                  )}
                  <AnimatePresence>
                    {p.total && (
                      <motion.div key="total" initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}
                        style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginTop: '0.6rem', paddingTop: '0.6rem', borderTop: '1px solid rgba(212,175,55,0.2)' }}>
                        <span style={{ color: 'rgba(255,255,255,0.22)', fontSize: '0.5rem', letterSpacing: '0.3em', textTransform: 'uppercase', fontWeight: 700, fontFamily: 'monospace' }}>{strings.total}</span>
                        <span style={{ color: '#fff', fontSize: '1.6rem', fontWeight: 900, letterSpacing: '-0.03em', fontVariantNumeric: 'tabular-nums', fontFamily: 'monospace' }}>
                          $<CountUp to={24497} running={p.total} />
                        </span>
                      </motion.div>
                    )}
                  </AnimatePresence>
                  <AnimatePresence>
                    {p.bid && (
                      <motion.div key="bid" initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} style={{ marginTop: '0.75rem' }}>
                        <div style={{ color: 'rgba(255,255,255,0.16)', fontSize: '0.46rem', letterSpacing: '0.3em', textTransform: 'uppercase', marginBottom: '0.4rem', fontFamily: 'monospace' }}>{strings.bidRange}</div>
                        <div style={{ position: 'relative', height: '2px', background: 'rgba(255,255,255,0.05)', borderRadius: '999px' }}>
                          <motion.div initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ duration: 0.9, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
                            style={{ position: 'absolute', inset: 0, background: 'linear-gradient(90deg, rgba(212,175,55,0.2), #D4AF37, rgba(212,175,55,0.2))', borderRadius: '999px', transformOrigin: 'left', boxShadow: '0 0 8px rgba(212,175,55,0.5)' }}
                          />
                          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1 }}
                            style={{ position: 'absolute', left: '58%', top: '-3px', width: '7px', height: '7px', borderRadius: '50%', background: '#D4AF37', transform: 'translateX(-50%)', boxShadow: '0 0 10px rgba(212,175,55,0.8)' }}
                          />
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '0.35rem', fontSize: '0.58rem', color: 'rgba(255,255,255,0.18)', fontVariantNumeric: 'tabular-nums', fontFamily: 'monospace' }}>
                          <span>$21,000</span><span style={{ color: '#D4AF37', fontWeight: 700 }}>$24,497</span><span>$28,000</span>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                  <AnimatePresence>
                    {p.exportBtn && (
                      <motion.div key="export" initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} style={{ marginTop: '1rem', display: 'flex', gap: '0.4rem' }}>
                        <motion.div
                          animate={{ boxShadow: ['0 0 0 0 rgba(212,175,55,0)', '0 0 20px 4px rgba(212,175,55,0.22)', '0 0 0 0 rgba(212,175,55,0)'] }}
                          transition={{ duration: 1.8, repeat: 2, ease: 'easeInOut' }}
                          style={{ flex: 1, background: 'linear-gradient(135deg, #BF953F, #D4AF37, #B38728)', color: '#0A0A0A', borderRadius: '4px', padding: '0.6rem 0.4rem', textAlign: 'center', fontSize: '0.56rem', fontWeight: 900, letterSpacing: '0.08em', textTransform: 'uppercase', fontFamily: 'monospace' }}
                        >
                          {strings.clientProposal}
                        </motion.div>
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }}
                          style={{ flex: 1, background: 'rgba(212,175,55,0.05)', border: '1px solid rgba(212,175,55,0.28)', color: '#D4AF37', borderRadius: '4px', padding: '0.6rem 0.4rem', textAlign: 'center', fontSize: '0.56rem', fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', fontFamily: 'monospace' }}
                        >
                          {strings.internalCost}
                        </motion.div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>

              </motion.div>
            )}

            {/* ── INTERNAL DOC OVERLAY ── */}
            {docScene === 'internal' && (
              <motion.div key="internal"
                initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, x: -24, filter: 'blur(6px)' }}
                transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
                style={{ flex: 1, background: '#0D0D0D', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}
              >
                {/* Dark header */}
                <div style={{ background: '#141414', padding: '0.75rem 1rem', borderBottom: '2px solid rgba(180,30,30,0.7)', flexShrink: 0 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div>
                      <div style={{ color: '#ffffff', fontSize: '0.62rem', fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', fontFamily: 'monospace' }}>{strings.internal.title}</div>
                      <div style={{ color: 'rgba(255,255,255,0.28)', fontSize: '0.5rem', marginTop: '0.12rem', fontFamily: 'monospace' }}>{strings.internal.subtitle}</div>
                    </div>
                    <div style={{ background: 'rgba(180,30,30,0.12)', border: '1px solid rgba(180,30,30,0.5)', borderRadius: '3px', padding: '0.18rem 0.5rem' }}>
                      <span style={{ color: '#ff6b6b', fontSize: '0.45rem', fontWeight: 700, letterSpacing: '0.18em', textTransform: 'uppercase', fontFamily: 'monospace' }}>{strings.internal.confidential}</span>
                    </div>
                  </div>
                </div>

                {/* Line items */}
                <div style={{ flex: 1, padding: '0.7rem 1rem', display: 'flex', flexDirection: 'column', gap: '0' }}>
                  {strings.internal.rows.map(([label, val], i) => (
                    <motion.div key={label}
                      initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }}
                      transition={{ duration: 0.35, delay: i * 0.1, ease: [0.16, 1, 0.3, 1] }}
                      style={{ display: 'flex', justifyContent: 'space-between', padding: '0.38rem 0', borderBottom: '1px solid rgba(255,255,255,0.04)' }}
                    >
                      <span style={{ color: 'rgba(255,255,255,0.38)', fontSize: '0.65rem', fontFamily: 'monospace' }}>{label}</span>
                      <span style={{ color: '#fff', fontSize: '0.68rem', fontWeight: 600, fontVariantNumeric: 'tabular-nums', fontFamily: 'monospace' }}>{val}</span>
                    </motion.div>
                  ))}

                  {/* Direct cost */}
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.5 }}
                    style={{ background: '#141414', margin: '0.5rem -1rem', padding: '0.55rem 1rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span style={{ color: 'rgba(255,255,255,0.3)', fontSize: '0.5rem', letterSpacing: '0.22em', textTransform: 'uppercase', fontFamily: 'monospace' }}>{strings.internal.clientTotal}</span>
                    <span style={{ color: '#D4AF37', fontSize: '1.4rem', fontWeight: 900, letterSpacing: '-0.02em', fontVariantNumeric: 'tabular-nums', fontFamily: 'monospace' }}>$24,497</span>
                  </motion.div>

                  {/* Margin stats */}
                  <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.7, duration: 0.5 }}
                    style={{ display: 'flex', gap: '1.5rem', paddingTop: '0.6rem' }}>
                    {[
                      [strings.internal.grossMargin, '15.0%', '#3DBE6C'],
                      [strings.internal.netProfit, '$3,673', '#fff'],
                      [strings.internal.ref, strings.internal.refVal, 'rgba(255,255,255,0.4)'],
                    ].map(([label, val, col]) => (
                      <div key={label}>
                        <div style={{ fontSize: '0.44rem', color: 'rgba(255,255,255,0.22)', textTransform: 'uppercase', letterSpacing: '0.12em', fontFamily: 'monospace', marginBottom: '0.18rem' }}>{label}</div>
                        <div style={{ fontSize: '0.8rem', fontWeight: 800, color: col, fontVariantNumeric: 'tabular-nums', fontFamily: 'monospace' }}>{val}</div>
                      </div>
                    ))}
                  </motion.div>
                </div>
              </motion.div>
            )}

            {/* ── CLIENT PROPOSAL OVERLAY ── */}
            {docScene === 'proposal' && (
              <motion.div key="proposal"
                initial={{ opacity: 0, x: 28, scale: 0.97 }} animate={{ opacity: 1, x: 0, scale: 1 }} exit={{ opacity: 0 }}
                transition={{ duration: 0.55, ease: [0.16, 1, 0.3, 1] }}
                style={{ flex: 1, background: '#fafafa', color: '#111', display: 'flex', flexDirection: 'column', overflow: 'hidden', fontFamily: 'Inter, sans-serif' }}
              >
                {/* Proposal header */}
                <div style={{ background: '#0A0A0A', padding: '0.9rem 1rem', borderBottom: '2.5px solid #D4AF37', flexShrink: 0 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div>
                      <div style={{ color: '#D4AF37', fontSize: '0.72rem', fontWeight: 900, letterSpacing: '0.22em' }}>EVEN</div>
                      <div style={{ color: 'rgba(255,255,255,0.28)', fontSize: '0.48rem', letterSpacing: '0.06em', marginTop: '0.08rem' }}>by Cornerstone OS</div>
                    </div>
                    <div style={{ textAlign: 'right' }}>
                      <div style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.44rem', letterSpacing: '0.28em', textTransform: 'uppercase' }}>Client</div>
                      <div style={{ color: '#D4AF37', fontSize: '0.62rem', fontWeight: 700, letterSpacing: '0.18em', textTransform: 'uppercase' }}>Proposal</div>
                    </div>
                  </div>
                </div>

                {/* Project info */}
                <div style={{ padding: '0.75rem 1rem', borderBottom: '1px solid #ebebeb', background: '#fff', flexShrink: 0 }}>
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem', marginBottom: '0.6rem' }}>
                    <div>
                      <div style={{ fontSize: '0.44rem', color: '#bbb', textTransform: 'uppercase', letterSpacing: '0.18em', fontWeight: 600, marginBottom: '0.2rem' }}>{strings.proposal.preparedFor}</div>
                      <div style={{ fontSize: '0.78rem', fontWeight: 700, color: '#111' }}>{strings.proposal.clientName}</div>
                      <div style={{ fontSize: '0.6rem', color: '#888', marginTop: '0.08rem' }}>{strings.proposal.clientCity}</div>
                    </div>
                    <div style={{ textAlign: 'right' }}>
                      <div style={{ fontSize: '0.44rem', color: '#bbb', textTransform: 'uppercase', letterSpacing: '0.18em', fontWeight: 600, marginBottom: '0.2rem' }}>{strings.proposal.dateLabel}</div>
                      <div style={{ fontSize: '0.7rem', fontWeight: 600, color: '#111' }}>{strings.proposal.dateValue}</div>
                      <div style={{ fontSize: '0.56rem', color: '#ccc', marginTop: '0.08rem' }}>{strings.proposal.ref}</div>
                    </div>
                  </div>
                  <div style={{ fontSize: '0.68rem', fontWeight: 700, color: '#111' }}>{strings.proposal.jobDescription}</div>
                </div>

                {/* Scope */}
                <div style={{ padding: '0.7rem 1rem', borderBottom: '1px solid #ebebeb', background: '#fff' }}>
                  <div style={{ fontSize: '0.44rem', color: '#D4AF37', letterSpacing: '0.3em', textTransform: 'uppercase', fontWeight: 700, marginBottom: '0.55rem' }}>{strings.proposal.scopeTitle}</div>
                  {strings.proposal.scope.map((item, i) => (
                    <div key={i} style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.32rem', fontSize: '0.63rem', color: '#555', lineHeight: 1.35 }}>
                      <span style={{ color: '#D4AF37', fontWeight: 700, flexShrink: 0, marginTop: '0.04em' }}>·</span>
                      <span>{item}</span>
                    </div>
                  ))}
                </div>

                {/* Total with badge */}
                <div style={{ padding: '0.9rem 1rem', background: '#0A0A0A', borderBottom: '2.5px solid #D4AF37', flexShrink: 0, position: 'relative', overflow: 'hidden' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div style={{ color: 'rgba(255,255,255,0.35)', fontSize: '0.5rem', letterSpacing: '0.28em', textTransform: 'uppercase', fontWeight: 600 }}>{strings.proposal.totalLabel}</div>
                    <div style={{ position: 'relative', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <span style={{ color: '#D4AF37', fontSize: '1.55rem', fontWeight: 900, letterSpacing: '-0.02em', fontVariantNumeric: 'tabular-nums' }}>$24,497</span>
                      {/* Lock badge */}
                      <AnimatePresence>
                        {p.badge && (
                          <motion.div
                            initial={{ scale: 0, opacity: 0 }}
                            animate={{ scale: 1, opacity: 1 }}
                            transition={{ duration: 0.55, ease: [0.16, 1, 0.3, 1] }}
                            style={{ width: 20, height: 20, borderRadius: '50%', background: '#D4AF37', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}
                          >
                            <svg width="10" height="8" viewBox="0 0 10 8" fill="none">
                              <path d="M1 4L4 7L9 1" stroke="#0A0A0A" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  </div>
                  {/* Gold ring pulse on badge */}
                  {p.badge && (
                    <motion.div
                      initial={{ scale: 1, opacity: 0.6 }} animate={{ scale: 2.8, opacity: 0 }}
                      transition={{ duration: 1.0, ease: 'easeOut' }}
                      style={{ position: 'absolute', right: '1rem', top: '50%', width: 20, height: 20, borderRadius: '50%', border: '1.5px solid rgba(212,175,55,0.7)', transform: 'translateY(-50%)' }}
                    />
                  )}
                </div>

                {/* Payment terms */}
                <div style={{ padding: '0.65rem 1rem', background: '#fff' }}>
                  <div style={{ fontSize: '0.44rem', color: '#D4AF37', letterSpacing: '0.28em', textTransform: 'uppercase', fontWeight: 700, marginBottom: '0.5rem' }}>{strings.proposal.paymentTitle}</div>
                  {strings.proposal.payments.map(([label, val]) => (
                    <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '0.3rem 0', borderBottom: '1px solid #f2f2f2' }}>
                      <span style={{ fontSize: '0.62rem', color: '#777' }}>{label}</span>
                      <span style={{ fontSize: '0.65rem', fontWeight: 700, color: '#111', fontVariantNumeric: 'tabular-nums' }}>{val}</span>
                    </div>
                  ))}
                  <div style={{ textAlign: 'center', paddingTop: '0.6rem' }}>
                    <div style={{ fontSize: '0.44rem', color: '#ccc', letterSpacing: '0.2em', textTransform: 'uppercase' }}>{strings.proposal.footer}</div>
                  </div>
                </div>
              </motion.div>
            )}

          </AnimatePresence>
        </div>

        {/* Add to Home Screen */}
        <AnimatePresence>
          {p.addHome && !p.logo && showApp && (
            <motion.div key="add-home"
              initial={{ y: 60, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 60, opacity: 0 }}
              transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
              style={{ position: 'absolute', bottom: 28, left: 0, right: 0, background: 'rgba(14,14,14,0.98)', borderTop: '1px solid rgba(212,175,55,0.15)', padding: '0.7rem 1rem', display: 'flex', alignItems: 'center', gap: '0.6rem', zIndex: 30 }}
            >
              <div style={{ width: 30, height: 30, borderRadius: '7px', background: 'linear-gradient(135deg,#BF953F,#D4AF37)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <span style={{ color: '#0A0A0A', fontWeight: 900, fontSize: '0.7rem', fontFamily: 'monospace' }}>E</span>
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ color: '#fff', fontSize: '0.65rem', fontWeight: 600, marginBottom: '0.1rem' }}>{strings.addHome}</div>
                <div style={{ color: 'rgba(255,255,255,0.22)', fontSize: '0.55rem', fontFamily: 'monospace' }}>{strings.addHomeSub}</div>
              </div>
              <div style={{ color: 'rgba(255,255,255,0.15)', fontSize: '0.9rem' }}>×</div>
            </motion.div>
          )}
        </AnimatePresence>
      </PhoneFrame>

      {/* Logo end card */}
      <AnimatePresence>
        {p.logo && (
          <motion.div key="logo"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 1 }}
            style={{ position: 'absolute', bottom: '1.5rem', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.35rem' }}
          >
            <img src="/logo.png" alt="Even" style={{ height: '1rem', objectFit: 'contain' }} onError={e => { e.target.style.display = 'none' }} />
            <span style={{ color: '#D4AF37', fontSize: '0.45rem', letterSpacing: '0.35em', textTransform: 'uppercase', fontWeight: 700, fontFamily: 'monospace', textShadow: '0 0 12px rgba(212,175,55,0.4)' }}>even-os.com</span>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

export default function Explainer() {
  return <ExplainerBase strings={STRINGS_EN} />
}

export function ExplainerES() {
  return <ExplainerBase strings={STRINGS_ES} />
}
