import { useState, useEffect, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

// VOICE TIMESTAMPS — ElevenLabs post-production:
//   0:00 → estimate    EN: "Done. Estimate locked."          ES: "Listo. Estimado completado."
//   0:03 → docsSlide   EN: "One tap. Two documents."         ES: "Un toque. Dos documentos."
//   0:06 → proposal    EN: "Your client gets this."          ES: "Tu cliente recibe esto."
//   0:12 → internal    EN: "You keep this."                  ES: "Tú lo guardas."
//   0:18 → thumbs      [breath / silence]
//   0:19 → tagline     EN: "Your client sees this. You keep this."  ES: "Tu cliente ve esto. Tú lo guardas."

const LOOP = 27000

const PHASES = {
  estimate: 500,
  estimateRows: 1000,
  exportBtn: 2600,
  exportTap: 3400,
  docsSlide: 3800,
  proposalExpand: 6400,
  proposalScroll: 8000,
  internalExpand: 12500,
  internalRows: 13200,
  internalScroll: 14800,
  thumbs: 18800,
  tagline: 20600,
  logo: 22800,
}

const STRINGS_EN = {
  jobLabel: 'Roofing Replacement · Houston, TX',
  breakdown: { materials: 'Materials', labor: 'Labor', fees: 'Permits & Fees' },
  estimatedTotal: 'Estimated Total',
  exportBtn: 'Export ↗',
  clientProposalLabel: 'Client Proposal',
  internalCostLabel: 'Internal Cost',
  confidential: 'Confidential',
  sendingToClient: 'Sending to Client',
  internalSheetLabel: 'Internal Cost Sheet',
  youKeepThis: 'You Keep This',
  tagline: { part1: 'Your client sees this. ', part2: 'You keep this.' },
  endCard: { line1: 'You run the business.', line2: 'We run the numbers.' },
  proposal: {
    clientLabel: 'Client',
    proposalLabel: 'Proposal',
    preparedFor: 'Prepared For',
    clientName: 'J. Martinez',
    clientCity: 'Houston, TX 77001',
    dateLabel: 'Date',
    dateValue: 'June 28, 2026',
    ref: 'Ref: HTX-2681',
    jobDescription: 'Roofing Replacement — 3,200 sq ft',
    scopeTitle: 'Scope of Work',
    scope: [
      'Remove and dispose of existing roofing materials',
      'Install premium 30-year architectural shingles',
      'Replace underlayment and moisture barrier',
      'All permit filing and fees included',
      'Post-installation cleanup and final inspection',
    ],
    totalLabel: 'Total',
    paymentTitle: 'Payment Terms',
    payments: [
      ['Deposit due at signing', '$14,234'],
      ['Balance due on completion', '$14,234'],
    ],
    signatures: ['Client Signature', 'Contractor Signature'],
    sigLine: 'Signature',
    dateLine: 'Date',
    footer: 'Generated by Even · even-os.com',
  },
  internal: {
    title: 'Internal Cost Breakdown',
    subtitle: 'Roofing · Houston, TX · June 28, 2026',
    confidential: 'Confidential',
    headers: ['Item', 'Qty', 'Rate', 'Total'],
    lineItems: [
      { label: 'Shingles (30yr arch)', qty: '80 sq', rate: '$130', total: '$10,400' },
      { label: 'Underlayment + barrier', qty: '3,200 sf', rate: '$0.56', total: '$1,795' },
      { label: 'Misc materials & nails', qty: '—', rate: '—', total: '$600' },
      { label: 'Labor — tear-off', qty: '48 h', rate: '$48', total: '$2,304' },
      { label: 'Labor — install', qty: '96 h', rate: '$60', total: '$5,760' },
      { label: 'Labor — cleanup & PM', qty: '—', rate: '—', total: '$936' },
      { label: 'Permit fees', qty: '—', rate: '—', total: '$1,217' },
      { label: 'Overhead & G&A', qty: '—', rate: '12%', total: '$2,776' },
    ],
    totals: [['Direct Cost', '$25,788'], ['Markup (10.4%)', '$2,680']],
    clientTotalLabel: 'Client Total',
    stats: [['Gross Margin', '9.4%'], ['Net Profit', '$2,680'], ['Job Ref', 'HTX-2681']],
  },
}

const STRINGS_ES = {
  jobLabel: 'Reemplazo de Techo · Houston, TX',
  breakdown: { materials: 'Materiales', labor: 'Mano de Obra', fees: 'Permisos y Tarifas' },
  estimatedTotal: 'Total Estimado',
  exportBtn: 'Exportar ↗',
  clientProposalLabel: 'Propuesta al Cliente',
  internalCostLabel: 'Costo Interno',
  confidential: 'Confidencial',
  sendingToClient: 'Enviando al Cliente',
  internalSheetLabel: 'Hoja de Costos Internos',
  youKeepThis: 'Solo Para Ti',
  tagline: { part1: 'Tu cliente ve esto. ', part2: 'Tú lo guardas.' },
  endCard: { line1: 'Tú manejas el negocio.', line2: 'Nosotros manejamos los números.' },
  proposal: {
    clientLabel: 'Cliente',
    proposalLabel: 'Propuesta',
    preparedFor: 'Preparado Para',
    clientName: 'M. Reyes',
    clientCity: 'Houston, TX 77001',
    dateLabel: 'Fecha',
    dateValue: '28 de junio, 2026',
    ref: 'Ref: HTX-2681',
    jobDescription: 'Reemplazo de Techo — 3,200 pies²',
    scopeTitle: 'Alcance del Trabajo',
    scope: [
      'Retirar y desechar los materiales del techo existente',
      'Instalar tejas arquitectónicas premium de 30 años',
      'Reemplazar la base y la barrera de humedad',
      'Todos los permisos y tarifas incluidos',
      'Limpieza post-instalación e inspección final',
    ],
    totalLabel: 'Total',
    paymentTitle: 'Términos de Pago',
    payments: [
      ['Depósito al firmar', '$14,234'],
      ['Balance al completar', '$14,234'],
    ],
    signatures: ['Firma del Cliente', 'Firma del Contratista'],
    sigLine: 'Firma',
    dateLine: 'Fecha',
    footer: 'Generado por Even · even-os.com',
  },
  internal: {
    title: 'Desglose de Costos Internos',
    subtitle: 'Techo · Houston, TX · 28 jun, 2026',
    confidential: 'Confidencial',
    headers: ['Artículo', 'Cant.', 'Precio', 'Total'],
    lineItems: [
      { label: 'Tejas (30 años arq.)', qty: '80 sq', rate: '$130', total: '$10,400' },
      { label: 'Base + barrera', qty: '3,200 sf', rate: '$0.56', total: '$1,795' },
      { label: 'Mat. varios y clavos', qty: '—', rate: '—', total: '$600' },
      { label: 'Mano de obra — retiro', qty: '48 h', rate: '$48', total: '$2,304' },
      { label: 'Mano de obra — instalación', qty: '96 h', rate: '$60', total: '$5,760' },
      { label: 'Mano de obra — limpieza', qty: '—', rate: '—', total: '$936' },
      { label: 'Tarifas de permisos', qty: '—', rate: '—', total: '$1,217' },
      { label: 'Gastos generales', qty: '—', rate: '12%', total: '$2,776' },
    ],
    totals: [['Costo Directo', '$25,788'], ['Margen (10.4%)', '$2,680']],
    clientTotalLabel: 'Total del Cliente',
    stats: [['Margen Bruto', '9.4%'], ['Utilidad Neta', '$2,680'], ['Ref. Trabajo', 'HTX-2681']],
  },
}

// ─── PROPOSAL DOCUMENT ───────────────────────────────────────────────────────

function ProposalDoc({ s }) {
  return (
    <div style={{ width: '100%', background: '#fafafa', color: '#111', fontFamily: 'Inter, sans-serif' }}>
      {/* Header */}
      <div style={{ background: '#080808', padding: '1.25rem 1.5rem', borderBottom: '2.5px solid #D4AF37' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <div style={{ color: '#D4AF37', fontSize: '0.75rem', fontWeight: 800, letterSpacing: '0.25em' }}>EVEN</div>
            <div style={{ color: 'rgba(255,255,255,0.3)', fontSize: '0.52rem', letterSpacing: '0.08em', marginTop: '0.1rem' }}>by Cornerstone OS</div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ color: 'rgba(255,255,255,0.5)', fontSize: '0.48rem', letterSpacing: '0.3em', textTransform: 'uppercase' }}>{s.clientLabel}</div>
            <div style={{ color: '#D4AF37', fontSize: '0.68rem', fontWeight: 700, letterSpacing: '0.2em', textTransform: 'uppercase' }}>{s.proposalLabel}</div>
          </div>
        </div>
      </div>

      {/* Project info */}
      <div style={{ padding: '1rem 1.5rem', borderBottom: '1px solid #e8e8e8', background: '#fff' }}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '0.8rem' }}>
          <div>
            <div style={{ fontSize: '0.48rem', color: '#bbb', textTransform: 'uppercase', letterSpacing: '0.18em', fontWeight: 600, marginBottom: '0.25rem' }}>{s.preparedFor}</div>
            <div style={{ fontSize: '0.82rem', fontWeight: 700, color: '#111' }}>{s.clientName}</div>
            <div style={{ fontSize: '0.65rem', color: '#777', marginTop: '0.1rem' }}>{s.clientCity}</div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: '0.48rem', color: '#bbb', textTransform: 'uppercase', letterSpacing: '0.18em', fontWeight: 600, marginBottom: '0.25rem' }}>{s.dateLabel}</div>
            <div style={{ fontSize: '0.75rem', fontWeight: 600, color: '#111' }}>{s.dateValue}</div>
            <div style={{ fontSize: '0.6rem', color: '#bbb', marginTop: '0.1rem' }}>{s.ref}</div>
          </div>
        </div>
        <div style={{ fontSize: '0.7rem', fontWeight: 700, color: '#111' }}>{s.jobDescription}</div>
      </div>

      {/* Scope */}
      <div style={{ padding: '1rem 1.5rem', borderBottom: '1px solid #e8e8e8', background: '#fff' }}>
        <div style={{ fontSize: '0.48rem', color: '#D4AF37', letterSpacing: '0.32em', textTransform: 'uppercase', fontWeight: 700, marginBottom: '0.7rem' }}>{s.scopeTitle}</div>
        {s.scope.map((item, i) => (
          <div key={i} style={{ display: 'flex', gap: '0.6rem', marginBottom: '0.4rem', fontSize: '0.68rem', color: '#444', lineHeight: 1.4 }}>
            <span style={{ color: '#D4AF37', fontWeight: 700, flexShrink: 0, marginTop: '0.05em' }}>·</span>
            <span>{item}</span>
          </div>
        ))}
      </div>

      {/* Total */}
      <div style={{ padding: '1.1rem 1.5rem', background: '#080808', borderBottom: '2.5px solid #D4AF37' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ color: 'rgba(255,255,255,0.45)', fontSize: '0.52rem', letterSpacing: '0.28em', textTransform: 'uppercase', fontWeight: 600 }}>{s.totalLabel}</div>
          <div style={{ color: '#D4AF37', fontSize: '1.7rem', fontWeight: 900, letterSpacing: '-0.02em', fontVariantNumeric: 'tabular-nums' }}>$28,468</div>
        </div>
      </div>

      {/* Payment terms */}
      <div style={{ padding: '1rem 1.5rem', borderBottom: '1px solid #e8e8e8', background: '#fff' }}>
        <div style={{ fontSize: '0.48rem', color: '#D4AF37', letterSpacing: '0.32em', textTransform: 'uppercase', fontWeight: 700, marginBottom: '0.65rem' }}>{s.paymentTitle}</div>
        {s.payments.map(([label, val]) => (
          <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '0.35rem 0', borderBottom: '1px solid #f0f0f0' }}>
            <span style={{ fontSize: '0.67rem', color: '#666' }}>{label}</span>
            <span style={{ fontSize: '0.7rem', fontWeight: 700, color: '#111', fontVariantNumeric: 'tabular-nums' }}>{val}</span>
          </div>
        ))}
      </div>

      {/* Signatures */}
      <div style={{ padding: '1.5rem', background: '#fff', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
        {s.signatures.map(label => (
          <div key={label}>
            <div style={{ fontSize: '0.48rem', color: '#bbb', textTransform: 'uppercase', letterSpacing: '0.2em', fontWeight: 600, marginBottom: '0.9rem' }}>{label}</div>
            <div style={{ borderBottom: '1px solid #d0d0d0', marginBottom: '0.3rem' }} />
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.52rem', color: '#ccc' }}>
              <span>{s.sigLine}</span><span>{s.dateLine}</span>
            </div>
          </div>
        ))}
        <div style={{ textAlign: 'center', borderTop: '1px solid #f0f0f0', paddingTop: '0.75rem' }}>
          <div style={{ fontSize: '0.48rem', color: '#ccc', letterSpacing: '0.22em', textTransform: 'uppercase' }}>{s.footer}</div>
        </div>
      </div>
    </div>
  )
}

// ─── INTERNAL DOCUMENT ────────────────────────────────────────────────────────

function InternalDoc({ s, rowsVisible, instant }) {
  return (
    <div style={{ width: '100%', background: '#fafafa', color: '#111', fontFamily: 'Inter, sans-serif', position: 'relative', overflow: 'hidden' }}>
      {/* CONFIDENTIAL watermark */}
      <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none', zIndex: 0, overflow: 'hidden' }}>
        <div style={{ transform: 'rotate(-32deg)', color: 'rgba(200,30,30,0.055)', fontSize: '2.8rem', fontWeight: 900, letterSpacing: '0.12em', textTransform: 'uppercase', whiteSpace: 'nowrap', userSelect: 'none' }}>
          {s.confidential}
        </div>
      </div>

      {/* Header */}
      <div style={{ background: '#080808', padding: '1.25rem 1.5rem', borderBottom: '2.5px solid rgba(200,30,30,0.8)', position: 'relative', zIndex: 1 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div style={{ color: '#fff', fontSize: '0.68rem', fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase' }}>{s.title}</div>
            <div style={{ color: 'rgba(255,255,255,0.3)', fontSize: '0.52rem', marginTop: '0.15rem' }}>{s.subtitle}</div>
          </div>
          <div style={{ background: 'rgba(200,30,30,0.12)', border: '1px solid rgba(200,30,30,0.5)', borderRadius: '2px', padding: '0.2rem 0.55rem' }}>
            <span style={{ color: '#ff6b6b', fontSize: '0.48rem', fontWeight: 700, letterSpacing: '0.2em', textTransform: 'uppercase' }}>{s.confidential}</span>
          </div>
        </div>
      </div>

      {/* Line items */}
      <div style={{ padding: '1rem 1.5rem', position: 'relative', zIndex: 1, background: '#fff' }}>
        {/* Table header */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 52px 44px 56px', gap: '0.25rem', padding: '0.25rem 0', borderBottom: '1.5px solid #e0e0e0', marginBottom: '0.1rem' }}>
          {s.headers.map((h, i) => (
            <div key={h} style={{ fontSize: '0.48rem', fontWeight: 700, color: '#aaa', letterSpacing: '0.18em', textTransform: 'uppercase', textAlign: i > 0 ? 'right' : 'left' }}>{h}</div>
          ))}
        </div>

        {s.lineItems.map((item, i) => (
          <motion.div
            key={i}
            initial={{ opacity: instant ? 1 : 0, x: instant ? 0 : -8 }}
            animate={{ opacity: rowsVisible ? 1 : 0, x: rowsVisible ? 0 : -8 }}
            transition={{ duration: 0.32, delay: instant ? 0 : i * 0.1 }}
            style={{ display: 'grid', gridTemplateColumns: '1fr 52px 44px 56px', gap: '0.25rem', padding: '0.38rem 0', borderBottom: '1px solid #f3f3f3' }}
          >
            <span style={{ fontSize: '0.64rem', color: '#333' }}>{item.label}</span>
            <span style={{ fontSize: '0.6rem', color: '#999', textAlign: 'right', fontVariantNumeric: 'tabular-nums' }}>{item.qty}</span>
            <span style={{ fontSize: '0.6rem', color: '#999', textAlign: 'right', fontVariantNumeric: 'tabular-nums' }}>{item.rate}</span>
            <span style={{ fontSize: '0.65rem', color: '#111', fontWeight: 600, textAlign: 'right', fontVariantNumeric: 'tabular-nums' }}>{item.total}</span>
          </motion.div>
        ))}

        {/* Totals */}
        <motion.div initial={{ opacity: instant ? 1 : 0 }} animate={{ opacity: rowsVisible ? 1 : 0 }} transition={{ delay: instant ? 0 : 0.92 }}>
          {s.totals.map(([l, v]) => (
            <div key={l} style={{ display: 'flex', justifyContent: 'space-between', padding: '0.38rem 0', borderBottom: '1px solid #f0f0f0' }}>
              <span style={{ fontSize: '0.64rem', color: '#666' }}>{l}</span>
              <span style={{ fontSize: '0.66rem', fontWeight: 600, fontVariantNumeric: 'tabular-nums' }}>{v}</span>
            </div>
          ))}
        </motion.div>

        <motion.div initial={{ opacity: instant ? 1 : 0 }} animate={{ opacity: rowsVisible ? 1 : 0 }} transition={{ delay: instant ? 0 : 1.1 }}
          style={{ background: '#080808', margin: '0.6rem -1.5rem', padding: '0.8rem 1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.52rem', letterSpacing: '0.24em', textTransform: 'uppercase' }}>{s.clientTotalLabel}</span>
          <span style={{ color: '#D4AF37', fontSize: '1.3rem', fontWeight: 900, letterSpacing: '-0.02em', fontVariantNumeric: 'tabular-nums' }}>$28,468</span>
        </motion.div>

        <motion.div initial={{ opacity: instant ? 1 : 0 }} animate={{ opacity: rowsVisible ? 1 : 0 }} transition={{ delay: instant ? 0 : 1.25 }}
          style={{ display: 'flex', gap: '2rem', paddingTop: '0.75rem' }}>
          {s.stats.map(([l, v]) => (
            <div key={l}>
              <div style={{ fontSize: '0.47rem', color: '#bbb', textTransform: 'uppercase', letterSpacing: '0.12em', marginBottom: '0.2rem' }}>{l}</div>
              <div style={{ fontSize: '0.82rem', fontWeight: 800, color: '#111', fontVariantNumeric: 'tabular-nums' }}>{v}</div>
            </div>
          ))}
        </motion.div>
      </div>
    </div>
  )
}

// ─── SCALED THUMBNAIL ─────────────────────────────────────────────────────────

function DocThumb({ children, label, badge, badgeColor = '#D4AF37' }) {
  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <span style={{ color: 'rgba(255,255,255,0.35)', fontSize: '0.52rem', letterSpacing: '0.18em', textTransform: 'uppercase', fontWeight: 600 }}>{label}</span>
        {badge && <span style={{ color: badgeColor, fontSize: '0.46rem', letterSpacing: '0.16em', textTransform: 'uppercase', fontWeight: 700 }}>{badge}</span>}
      </div>
      <div style={{
        overflow: 'hidden', borderRadius: '4px',
        boxShadow: '0 8px 40px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.06)',
        height: 240, position: 'relative',
      }}>
        <div style={{ transform: 'scale(0.44)', transformOrigin: 'top left', width: 'calc(100% / 0.44)', pointerEvents: 'none' }}>
          {children}
        </div>
      </div>
    </div>
  )
}

// ─── MAIN COMPONENT ───────────────────────────────────────────────────────────

function TwoOutputsBase({ strings: t }) {
  const [p, setP] = useState({})
  const timers = useRef([])

  function reset() {
    timers.current.forEach(clearTimeout)
    timers.current = []
    setP({})
  }

  function run() {
    reset()
    Object.entries(PHASES).forEach(([key, delay]) => {
      timers.current.push(setTimeout(() => setP(prev => ({ ...prev, [key]: true })), delay))
    })
    timers.current.push(setTimeout(run, LOOP))
  }

  useEffect(() => { run(); return reset }, [])

  const scene = p.logo ? 'end'
    : p.thumbs ? 'thumbs'
    : p.internalExpand ? 'internal'
    : p.proposalExpand ? 'proposal'
    : p.docsSlide ? 'docs'
    : p.estimate ? 'estimate'
    : null

  return (
    <div style={{
      width: '100vw', height: '100vh', background: '#080808',
      backgroundImage: "repeating-linear-gradient(60deg,rgba(212,175,55,0.032) 0,rgba(212,175,55,0.032) 1px,transparent 0,transparent 50%),repeating-linear-gradient(-60deg,rgba(212,175,55,0.032) 0,rgba(212,175,55,0.032) 1px,transparent 0,transparent 50%)",
      backgroundSize: '28px 48px',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontFamily: 'Inter, sans-serif', overflow: 'hidden', position: 'relative',
    }}>
      <AnimatePresence mode="wait">

        {/* ── ESTIMATE RESULT ── */}
        {scene === 'estimate' && (
          <motion.div key="estimate"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, scale: 0.96, filter: 'blur(4px)' }}
            transition={{ duration: 0.38, ease: [0.4, 0, 1, 1] }}
            style={{ textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.75rem', padding: '0 2rem', width: '100%', maxWidth: '380px' }}
          >
            {/* Job label */}
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.1 }}
              style={{ color: 'rgba(255,255,255,0.28)', fontSize: '0.58rem', letterSpacing: '0.25em', textTransform: 'uppercase' }}>
              {t.jobLabel}
            </motion.div>

            {/* Cost breakdown rows */}
            <AnimatePresence>
              {p.estimateRows && (
                <motion.div
                  initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3 }}
                  style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: '0' }}
                >
                  {[
                    { label: t.breakdown.materials, value: '$12,795' },
                    { label: t.breakdown.labor, value: '$9,000' },
                    { label: t.breakdown.fees, value: '$3,993' },
                  ].map(({ label, value }, i) => (
                    <motion.div
                      key={label}
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ duration: 0.38, delay: i * 0.12, ease: [0.16, 1, 0.3, 1] }}
                      style={{
                        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                        padding: '0.55rem 0',
                        borderBottom: i < 2 ? '1px solid rgba(255,255,255,0.06)' : 'none',
                      }}
                    >
                      <span style={{ color: 'rgba(255,255,255,0.38)', fontSize: '0.64rem', letterSpacing: '0.06em' }}>{label}</span>
                      <span style={{ color: 'rgba(255,255,255,0.6)', fontSize: '0.72rem', fontWeight: 600, fontVariantNumeric: 'tabular-nums' }}>{value}</span>
                    </motion.div>
                  ))}

                  {/* Divider before total */}
                  <motion.div
                    initial={{ scaleX: 0 }} animate={{ scaleX: 1 }}
                    transition={{ duration: 0.5, delay: 0.4, ease: [0.16, 1, 0.3, 1] }}
                    style={{ height: '1px', background: 'linear-gradient(90deg, #D4AF37, rgba(212,175,55,0.2))', margin: '0.6rem 0', transformOrigin: 'left' }}
                  />
                </motion.div>
              )}
            </AnimatePresence>

            {/* Total */}
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: p.estimateRows ? 1 : 0, y: p.estimateRows ? 0 : 10 }}
              transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
              style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.3rem' }}
            >
              <div style={{ color: '#D4AF37', fontSize: 'clamp(2.8rem, 13vw, 4.2rem)', fontWeight: 900, letterSpacing: '-0.04em', lineHeight: 1, fontVariantNumeric: 'tabular-nums' }}>
                $28,468
              </div>
              <div style={{ color: 'rgba(255,255,255,0.22)', fontSize: '0.57rem', letterSpacing: '0.22em', textTransform: 'uppercase' }}>
                {t.estimatedTotal}
              </div>
            </motion.div>

            {/* Export button */}
            <AnimatePresence>
              {p.exportBtn && (
                <motion.div
                  initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }}
                  style={{ marginTop: '0.4rem' }}
                >
                  <motion.div
                    animate={p.exportTap ? { scale: [1, 0.93, 1] } : { boxShadow: ['0 0 0 0 rgba(212,175,55,0)', '0 0 18px 4px rgba(212,175,55,0.2)', '0 0 0 0 rgba(212,175,55,0)'] }}
                    transition={p.exportTap ? { duration: 0.18 } : { duration: 1.8, repeat: 2, ease: 'easeInOut' }}
                    style={{
                      background: '#D4AF37', color: '#080808',
                      padding: '0.75rem 2rem', borderRadius: '4px',
                      fontSize: '0.75rem', fontWeight: 800, letterSpacing: '0.15em', textTransform: 'uppercase',
                    }}
                  >
                    {t.exportBtn}
                  </motion.div>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        )}

        {/* ── TWO DOCS SLIDE UP ── */}
        {scene === 'docs' && (
          <motion.div key="docs"
            initial={{ opacity: 1 }} animate={{ opacity: 1 }} exit={{ opacity: 0, filter: 'blur(4px)' }}
            transition={{ duration: 0.38 }}
            style={{ width: '100%', padding: '0 1rem', display: 'flex', gap: '0.75rem' }}
          >
            {[
              { delay: 0, label: t.clientProposalLabel, badge: null, content: <ProposalDoc s={t.proposal} /> },
              { delay: 0.06, label: t.internalCostLabel, badge: t.confidential, badgeColor: '#ff6b6b', content: <InternalDoc s={t.internal} rowsVisible instant /> },
            ].map(({ delay, label, badge, badgeColor, content }) => (
              <motion.div
                key={label}
                initial={{ y: '60%', opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ duration: 0.65, delay, ease: [0.16, 1, 0.3, 1] }}
                style={{ flex: 1 }}
              >
                <DocThumb label={label} badge={badge} badgeColor={badgeColor}>
                  {content}
                </DocThumb>
              </motion.div>
            ))}
          </motion.div>
        )}

        {/* ── PROPOSAL FULL SCREEN ── */}
        {scene === 'proposal' && (
          <motion.div key="proposal"
            initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.96, filter: 'blur(4px)' }}
            transition={{ duration: 0.45, ease: [0.16, 1, 0.3, 1] }}
            style={{ position: 'absolute', inset: 0, overflowY: 'hidden', display: 'flex', flexDirection: 'column' }}
          >
            <div style={{ background: 'rgba(8,8,8,0.95)', padding: '0.5rem 1rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexShrink: 0, zIndex: 10 }}>
              <span style={{ color: 'rgba(255,255,255,0.3)', fontSize: '0.52rem', letterSpacing: '0.2em', textTransform: 'uppercase' }}>{t.clientProposalLabel}</span>
              <span style={{ color: '#D4AF37', fontSize: '0.52rem', letterSpacing: '0.12em', textTransform: 'uppercase', fontWeight: 700 }}>{t.sendingToClient}</span>
            </div>
            <div style={{ flex: 1, overflow: 'hidden', position: 'relative' }}>
              <motion.div
                animate={{ y: p.proposalScroll ? -280 : 0 }}
                transition={{ duration: 4, ease: [0.25, 0.46, 0.45, 0.94], delay: 0.5 }}
              >
                <ProposalDoc s={t.proposal} />
              </motion.div>
            </div>
          </motion.div>
        )}

        {/* ── INTERNAL FULL SCREEN ── */}
        {scene === 'internal' && (
          <motion.div key="internal"
            initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.96, filter: 'blur(4px)' }}
            transition={{ duration: 0.45, ease: [0.16, 1, 0.3, 1] }}
            style={{ position: 'absolute', inset: 0, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}
          >
            <div style={{ background: 'rgba(8,8,8,0.95)', padding: '0.5rem 1rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexShrink: 0, zIndex: 10 }}>
              <span style={{ color: 'rgba(255,255,255,0.3)', fontSize: '0.52rem', letterSpacing: '0.2em', textTransform: 'uppercase' }}>{t.internalSheetLabel}</span>
              <span style={{ color: '#ff6b6b', fontSize: '0.52rem', letterSpacing: '0.12em', textTransform: 'uppercase', fontWeight: 700 }}>{t.youKeepThis}</span>
            </div>
            <div style={{ flex: 1, overflow: 'hidden', position: 'relative' }}>
              <motion.div
                animate={{ y: p.internalScroll ? -260 : 0 }}
                transition={{ duration: 3.8, ease: [0.25, 0.46, 0.45, 0.94], delay: 1.4 }}
              >
                <InternalDoc s={t.internal} rowsVisible={p.internalRows} instant={false} />
              </motion.div>
            </div>
          </motion.div>
        )}

        {/* ── SIDE BY SIDE + TAGLINE ── */}
        {scene === 'thumbs' && (
          <motion.div key="thumbs"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, filter: 'blur(4px)' }}
            transition={{ duration: 0.5 }}
            style={{ width: '100%', padding: '0 1rem', display: 'flex', flexDirection: 'column', gap: '1.5rem', alignItems: 'center' }}
          >
            <div style={{ display: 'flex', gap: '0.75rem', width: '100%' }}>
              {[
                { delay: 0, label: t.clientProposalLabel, content: <ProposalDoc s={t.proposal} />, badge: null },
                { delay: 0.08, label: t.internalCostLabel, content: <InternalDoc s={t.internal} rowsVisible instant />, badge: t.confidential, badgeColor: '#ff6b6b' },
              ].map(({ delay, label, content, badge, badgeColor }) => (
                <motion.div key={label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay, duration: 0.5 }} style={{ flex: 1 }}>
                  <DocThumb label={label} badge={badge} badgeColor={badgeColor}>{content}</DocThumb>
                </motion.div>
              ))}
            </div>

            <AnimatePresence>
              {p.tagline && (
                <motion.div
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
                  style={{ textAlign: 'center' }}
                >
                  <span style={{ color: 'rgba(255,255,255,0.55)', fontSize: '0.75rem', fontWeight: 400, letterSpacing: '0.02em' }}>
                    {t.tagline.part1}
                  </span>
                  <span style={{ color: '#ffffff', fontSize: '0.75rem', fontWeight: 700, letterSpacing: '0.02em' }}>
                    {t.tagline.part2}
                  </span>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        )}

        {/* ── END CARD ── */}
        {scene === 'end' && (
          <motion.div key="end"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 1 }}
            style={{ textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.75rem' }}
          >
            <motion.div initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
              style={{ height: '1px', width: '2.5rem', background: '#D4AF37', transformOrigin: 'center', marginBottom: '0.5rem' }}
            />
            <img src="/logo.png" alt="Even" style={{ height: '1.6rem', objectFit: 'contain' }} onError={e => { e.target.style.display = 'none' }} />
            <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5, duration: 0.7 }}>
              <div style={{ color: '#ffffff', fontSize: '0.82rem', fontWeight: 300, letterSpacing: '-0.01em' }}>{t.endCard.line1}</div>
              <div style={{ color: '#ffffff', fontSize: '0.82rem', fontWeight: 800, letterSpacing: '-0.01em' }}>{t.endCard.line2}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.1 }}
              style={{ color: '#D4AF37', fontSize: '0.5rem', letterSpacing: '0.35em', textTransform: 'uppercase', fontWeight: 600 }}>
              even-os.com
            </motion.div>
          </motion.div>
        )}

      </AnimatePresence>
    </div>
  )
}

export default function TwoOutputs() {
  return <TwoOutputsBase strings={STRINGS_EN} />
}

export function TwoOutputsES() {
  return <TwoOutputsBase strings={STRINGS_ES} />
}
